apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
     name: redis-pod
     app: myapp
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: myapp

    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379

