apiVersion: v1
kind: Service
metadata:
  name: image-processing
  labels:
    app: myapp
    
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
     tier: backend
