apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    tier: backend
spec:
  replicas: 2
  template:
    metadata:
      name: redis
      labels:
        tier: backend
    spec:
      containers:
        - name: redis
          image: redis
  selector:
    matchLabels:
      tier: backend
