apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
     name: web-pod
     app: myapp
  template:
    metadata:
      name: web-pod
      labels:
        name: web-pod
        app: myapp

    spec:
      containers:
      - name: web
        image: gcr.io/google-samples/gb-frontend:v4
        ports:
          - containerPort: 80

