apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    name: web-app-pod
    app: demo-web-app

spec:
  containers:
  - name: web-app
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
      - containerPort: 80
